[project]
name = "ssl-plotting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "nbformat>=5.10.4",
    "numpy>=2.3.3",
    "plotly>=6.3.1",
    "ruff>=0.13.3",
]
